# -*- coding: utf-8 -*-
"""Dumbbell Curl Counter AI.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmHcyFYOoKhLEU_gmKhKSE2s5PWzZPOR
"""

!pip install ultralytics

from ultralytics import YOLO

model = YOLO("yolo11n-pose.pt")

print("Model Loaded")

from google.colab import files

uploaded = files.upload()

!ls

results = model.predict(
    source="7187424-hd_1920_1080_24fps.mp4",
    save=True,
    conf=0.5
)

!ls runs/pose/predict

from IPython.display import Video

Video(
    "runs/pose/predict/7187424-hd_1920_1080_24fps.mp4",
    embed=True
)

!find runs -type f

!ls -lh runs/pose/predict

results = model.predict(
    source="7187424-hd_1920_1080_24fps.mp4",
    save=False
)

print(type(results))
print(len(results))

r = results[0]

print(r.keypoints)

print(r.keypoints.xy.shape)

"""1 person,

17 body keypoints,

(x,y) coordinates
"""

print(r.keypoints.xy[0])

print(r.keypoints.xy.shape)

print(r.keypoints.xy[0])

#Extract Shoulder, Elbow, Wrist

import numpy as np

pts = r.keypoints.xy[0].cpu().numpy()

right_shoulder = pts[6]
right_elbow    = pts[8]
right_wrist    = pts[10]

print("Shoulder:", right_shoulder)
print("Elbow:", right_elbow)
print("Wrist:", right_wrist)

#Angle Function

import numpy as np

def calculate_angle(a, b, c):

    a = np.array(a)
    b = np.array(b)
    c = np.array(c)

    radians = np.arctan2(
        c[1]-b[1],
        c[0]-b[0]
    ) - np.arctan2(
        a[1]-b[1],
        a[0]-b[0]
    )

    angle = np.abs(radians * 180 / np.pi)

    if angle > 180:
        angle = 360 - angle

    return angle

#Calculate Elbow Angle

angle = calculate_angle(
    right_shoulder,
    right_elbow,
    right_wrist
)

print("Elbow Angle =", angle)

"""Elbow Angle = 20.27°

This means the arm is fully bent, exactly what we expect at the top of a dumbbell curl.

160° - 180°  → Arm straight

20° - 40°    → Arm curled

So your angle calculation is working correctly
"""

#Count Repetitions

import cv2

cap = cv2.VideoCapture(
    "7187424-hd_1920_1080_24fps.mp4"
)

frame_count = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    frame_count += 1

cap.release()

print("Frames =", frame_count)

"""Frames = 168,

Elbow Angle = 20.27°
"""

#Person
#Holding dumbbell
#Performing bicep curls

counter = 0
stage = None

if angle > 160:
    stage = "down"

if angle < 40 and stage == "down":
    stage = "up"
    counter += 1

"""Straight Arm
   ↓
Bent Arm
   ↓
Straight Arm

= 1 Rep
"""

#Upload a real dumbbell curl video

from google.colab import files

uploaded = files.upload()

!ls

counter = 0
stage = None

angles = []

#Create Angle Function

import numpy as np

def calculate_angle(a, b, c):
    a = np.array(a)
    b = np.array(b)
    c = np.array(c)

    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - \
              np.arctan2(a[1]-b[1], a[0]-b[0])

    angle = np.abs(radians * 180.0 / np.pi)

    if angle > 180:
        angle = 360 - angle

    return angle

#Process Entire Video

import cv2
from ultralytics import YOLO

model = YOLO("yolo11n-pose.pt")

video_path = "7187424-hd_1920_1080_24fps.mp4"

cap = cv2.VideoCapture(video_path)

counter = 0
stage = None

frame_no = 0

while True:

    ret, frame = cap.read()

    if not ret:
        break

    frame_no += 1

    # Process every 3rd frame (faster)
    if frame_no % 3 != 0:
        continue

    results = model(frame, verbose=False)

    if len(results) == 0:
        continue

    if results[0].keypoints is None:
        continue

    pts = results[0].keypoints.xy

    if len(pts) == 0:
        continue

    pts = pts[0].cpu().numpy()

    right_shoulder = pts[6]
    right_elbow = pts[8]
    right_wrist = pts[10]

    angle = calculate_angle(
        right_shoulder,
        right_elbow,
        right_wrist
    )

    # Curl logic
    if angle > 150:
        stage = "down"

    if angle < 50 and stage == "down":
        stage = "up"
        counter += 1

        print("Rep:", counter)

cap.release()

print("\nTotal Repetitions =", counter)

"""Video
  ↓
YOLO Pose
  ↓
Body Keypoints
  ↓
Elbow Angle
  ↓
Rep Counter
  ↓
Total Repetitions
"""

#Create Gradio Web App

import gradio as gr
import cv2
import numpy as np
from ultralytics import YOLO

model = YOLO("yolo11n-pose.pt")

def calculate_angle(a, b, c):

    a = np.array(a)
    b = np.array(b)
    c = np.array(c)

    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - \
              np.arctan2(a[1]-b[1], a[0]-b[0])

    angle = np.abs(radians * 180 / np.pi)

    if angle > 180:
        angle = 360 - angle

    return angle


def count_reps(video_path):

    cap = cv2.VideoCapture(video_path)

    counter = 0
    stage = None

    frame_no = 0

    while True:

        ret, frame = cap.read()

        if not ret:
            break

        frame_no += 1

        if frame_no % 3 != 0:
            continue

        results = model(frame, verbose=False)

        if len(results) == 0:
            continue

        if results[0].keypoints is None:
            continue

        pts = results[0].keypoints.xy

        if len(pts) == 0:
            continue

        pts = pts[0].cpu().numpy()

        shoulder = pts[6]
        elbow = pts[8]
        wrist = pts[10]

        angle = calculate_angle(
            shoulder,
            elbow,
            wrist
        )

        if angle > 150:
            stage = "down"

        if angle < 50 and stage == "down":
            stage = "up"
            counter += 1

    cap.release()

    return f"Total Repetitions: {counter}"

#Launch Gradio

demo = gr.Interface(
    fn=count_reps,
    inputs=gr.Video(),
    outputs="text",
    title="Dumbbell Curl Counter AI"
)

demo.launch(share=True)
